# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
theme: panthera-jekyll
description: >- # this means to ignore newlines until "baseurl:"
left_side:
  background_image: /assets/img/cover.jpg
  background_color: [CSS background color, e.g. "#F00". We strongly recommend quoting this value. Don't worry about the transparency of the background, we've taken care of that.]
  close_button_color: [CSS background color, e.g. "#F00". We strongly recommend quoting this value.]
  text_color: [CSS background color, e.g. "#F00". We strongly recommend quoting this value.]
menu:
  - text: Portfolio
    link: /
    icon: ""
social_icons:
  - name: [Email]
    link: [https://yanglixin621@gmail.com]
    icon: [fas fa-envelope]
  - name: [Twitter]
    link: [https://twitter.com/vszhub]
    icon: [fab fa-twitter]
  - name: [Zhihu]
    link: [https://www.zhihu.com/people/li-xin-32-2]
    icon: [fab fa-zhihu]
  - name: [Github]
    link: [https://github.com/LixvYang]
    icon: [fab fa-github-alt]
footer:
  copyright_text: "Copyright LixvYang"


# Build settings
plugins:
  - jekyll-remote-theme
remote_theme: christianezeani/panthera-jekyll
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the   `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
